export const PENDING = 'PENDING'
export const SUCCESS = 'SUCCESS'
export const FAILED = 'FAILED'
export const REJECTED = 'REJECTED'
export const EMPTY = 'EMPTY'

export const FETCH = 'FETCH'
export const ADD = 'ADD'
export const DELETE = 'DELETE'
export const UPDATE = 'UPDATE'
